# Generated by Django 6.0.4 on 2026-04-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_customer_address_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
