# Generated by Django 6.0.4 on 2026-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_contract_contract_number_alter_contract_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingsubmission',
            name='previous_reading',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
