# Generated by Django 6.0.4 on 2026-04-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_meterreadingsubmission_previous_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='previous_reading',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreadingsubmission',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billing.billingperiod'),
        ),
        migrations.AlterField(
            model_name='meterreadingsubmission',
            name='reading_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
