# Generated by Django 6.0.4 on 2026-04-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_meterreading_previous_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingsubmission',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.contract'),
        ),
        migrations.AlterField(
            model_name='meterreadingsubmission',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.customer'),
        ),
    ]
