# Generated by Django 6.0.4 on 2026-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_meterreadingsubmission_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='last_approved_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
