# Generated by Django 6.0.4 on 2026-04-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_payment_contract_alter_payment_invoice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meterreadingsubmission',
            unique_together={('meter', 'reading_date')},
        ),
    ]
