# Generated by Django 6.0.4 on 2026-04-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_meterreadingsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meterreadingsubmission',
            unique_together=set(),
        ),
    ]
