# Generated by Django 6.0.4 on 2026-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_meterreadingsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
