# Generated by Django 6.0.4 on 2026-04-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_route_route_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelinetemplate',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicelinetemplate',
            name='percentage_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
