# Generated by Django 6.0.4 on 2026-04-29 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_invoiceline_quantity_invoiceline_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.billingperiod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.billingperiod'),
        ),
    ]
