# Generated by Django 6.0.4 on 2026-04-29 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoice_period_payment_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='reader_name',
        ),
        migrations.AddField(
            model_name='meterreading',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
