# Generated by Django 6.0.4 on 2026-04-29 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_remove_meterreading_reader_name_meterreading_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscriptiontype'),
        ),
    ]
