# Generated by Django 6.0.4 on 2026-04-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_remove_meterreadingsubmission_reader_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='previous_indebtedness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
