# Generated by Django 6.0.4 on 2026-05-13 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0019_invoice_previous_indebtedness'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allow_overlap', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Date Range Type',
                'verbose_name_plural': 'Date Range Types',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('journal_type', models.CharField(choices=[('sales', 'Sales'), ('purchases', 'Purchases'), ('cash', 'Cash'), ('bank', 'Bank'), ('general', 'General')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('recurring_invoice', 'Recurring Invoice'), ('meter_reading', 'Meter Reading'), ('notification', 'Notification'), ('report', 'Report Generation'), ('custom', 'Custom')], default='recurring_invoice', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('payload', models.TextField(blank=True, default='{}')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task Queue',
                'verbose_name_plural': 'Task Queues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('factor', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
            },
        ),
        migrations.CreateModel(
            name='UoMCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'UoM Category',
                'verbose_name_plural': 'UoM Categories',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('partner_old_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_number', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_type', models.CharField(choices=[('meck', 'Mechanical'), ('elec', 'Electronic'), ('ppay', 'Prepaid')], default='meck', max_length=20)),
                ('meter_phase_type', models.CharField(choices=[('1vas', 'Single Phase'), ('3vas', 'Three Phase'), ('allvas', 'Transformer')], default='1vas', max_length=20)),
                ('meter_usage_type', models.CharField(choices=[('home', 'Home'), ('trad', 'Commercial'), ('gover', 'Government'), ('manve', 'Industrial'), ('water', 'Water Pump'), ('other', 'Other')], default='home', max_length=20)),
                ('meter_first_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meter_current_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meter_last_invoice_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meter_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('recurring_invoices', models.BooleanField(default=False)),
                ('recurring_rule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('recurring_interval', models.IntegerField(default=1)),
                ('recurring_invoicing_type', models.CharField(choices=[('pre-paid', 'Pre-paid'), ('post-paid', 'Post-paid')], default='post-paid', max_length=20)),
                ('recurring_next_date', models.DateField(blank=True, null=True)),
                ('connection_date', models.DateField(blank=True, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract_management.journal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_range_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='contract_management.daterangetype')),
            ],
            options={
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateTimeField()),
                ('reading_type', models.CharField(choices=[('regular', 'Regular'), ('invoice', 'Invoice')], default='regular', max_length=20)),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='contract_management.contract')),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('contract_type', models.CharField(blank=True, choices=[('ELECTRIC', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas')], default='', max_length=20)),
                ('pricing_type', models.CharField(choices=[('FLAT', 'Fixed Fee'), ('PER_UNIT', 'Per Unit'), ('TIERED', 'Tiered Pricing')], default='FLAT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tier_from', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier_to', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract_management.uom')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_template', models.BooleanField(default=False)),
                ('contract_type', models.CharField(blank=True, choices=[('ELECTRIC', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas')], default='', max_length=20)),
                ('pricing_type', models.CharField(choices=[('FLAT', 'Fixed Fee'), ('PER_UNIT', 'Per Unit'), ('TIERED', 'Tiered Pricing')], default='FLAT', max_length=20)),
                ('tier_from', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier_to', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sequence', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contract_management.contract')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract_management.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract_management.uom')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='uom',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract_management.uomcategory'),
        ),
    ]
