# Generated by Django 6.0.4 on 2026-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('electric', 'كهرباء'), ('water', 'مياه')], default='electric', max_length=20),
        ),
    ]
