# Generated by Django 6.0.4 on 2026-05-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_tenant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_type',
        ),
    ]
