# Generated by Django 6.0.4 on 2026-05-14 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_tenant_tenant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'اشتراك جديد'), ('upgraded', 'ترقية'), ('downgraded', 'تخفيض'), ('renewed', 'تجديد'), ('cancelled', 'إلغاء'), ('payment', 'دفعة')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('succeeded', 'ناجحة'), ('failed', 'فاشلة'), ('refunded', 'مستردة')], default='succeeded', max_length=20)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_from', to='tenants.plan')),
                ('plan_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_to', to='tenants.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'سجل الاشتراكات',
                'ordering': ['-created_at'],
            },
        ),
    ]
