# Generated by Django 6.0.4 on 2026-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_monthly',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id_yearly',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='stripe_invoice_id',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='payment_gateway',
            field=models.CharField(blank=True, help_text='بوابة الدفع المستخدمة', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='رقم العملية من بوابة الدفع', max_length=200),
        ),
    ]
