# Generated by Django 6.0.4 on 2026-05-13 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('PAYMENT', 'Payment'), ('COMMUNICATION', 'Communication'), ('CRM', 'CRM'), ('ACCOUNTING', 'Accounting'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('documentation_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('auth_type', models.CharField(choices=[('API_KEY', 'API Key'), ('BASIC_AUTH', 'Basic Auth'), ('BEARER_TOKEN', 'Bearer Token'), ('OAUTH2', 'OAuth2'), ('CUSTOM', 'Custom JSON')], default='API_KEY', max_length=20)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('LIVE', 'Live')], default='SANDBOX', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='integrations.integration')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('endpoint', models.CharField(blank=True, default='', max_length=500)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True, default='')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('is_success', models.BooleanField(default=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integrationconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
